name: Java NPM CI - TIP WLAN Cloud UI Library

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Prepare repository
        run: |
          sudo npm i npmrc -g 
          npmrc -c tip-wlan
          npm config set @tip-wlan:registry https://tip.jfrog.io/artifactory/api/npm/tip-wlan-cloud-npm-repo/
          npm login --scope=tip-wlan --user=build-pipeline --email=build-pipeline@example.com --password=${{ secrets.NPM_REPO_PASSWORD }} --registry=https://tip.jfrog.io/artifactory/api/npm/tip-wlan-cloud-npm-repo/
      - name: Install webpack
        run: npm install --save-dev webpack@4.42.0 webpack-cli@3.3.11
      - name: Build npm module
        run: npm install
      - name: Publish npm module into tip-wlan-cloud-npm-repo
        run: npm publish --registry https://tip.jfrog.io/artifactory/api/npm/tip-wlan-cloud-npm-repo/

